language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -e .
  - pip install -r requirements.txt 
script:
  - py.test --cov . --cov-report xml:coverage.xml

# codeclimate coverage => change id to yours
env:
  global:
    - CC_TEST_REPORTER_ID=c61d8c42159f8fb7765c2fa2366b8ca48105d559506f900fdf6edfa0374cdde7

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
